
        <?php
            /*
            *
            * -------------------------------------------------------
            * CLASSNAME:        
            * GENERATION DATE:  06.03.2016
            * FOR MYSQL TABLE:  acesso
            * FOR MYSQL DB:     hcb_criancas
            * -------------------------------------------------------
            * CODE GENERATED BY:
            * @MURANO DESIGN
            * -------------------------------------------------------
            *
            */

            session_start();
            $path = $_SESSION['PATH_SYS'];
            include_once($path['DB'].'DataAccess.php');
            include_once($path['DB'].'DAO.php');
            include_once($path['beans'].'.php');


            /**
             * Description of DAO
             *
             * @author Ana Carolina
             */

            class DAO extends DAO{

                public function  __construct() {
                    parent::__construct();
                }

                 
                // **********************
                // INSERT
                // **********************

                public function insert($)
                {
                    $sql =  "insert into acesso ( prf_id,id_menu )values";
                    $sql .= "( '".$->getPrf_id()."','".$->getId_menu()."'");
                    return $this->execute($sql);
                }
            
                // **********************
                // DELETE
                // **********************

                public function delete($id)
                {
                    $sql = "delete from acesso where  = $id";
                    return $this->execute($sql);
                }
            
                // **********************
                // SELECT BY ID
                // **********************

                function selectById($id)
                {
                    $sql = "select * from acesso where  = ". $id."limit 1 ";
                    $result = $this->retrieve($sql);
                    $qr = mysql_fetch_array($result);
                    $= new ();
                    $->setPrf_id($qr[prf_id]);
$->setId_menu($qr[id_menu]);

                    return $;
                }
            
                // **********************
                // SELECT ALL
                // **********************

                function selectById($id)
                {
                    $sql = "select * from acesso ";
                    $lista = array();
                    $result = $this->retrieve($sql);
                    while ($qr = mysql_fetch_array($result)){
                    $= new ();
                    $->setPrf_id($qr[prf_id]);
$->setId_menu($qr[id_menu]);

                    array_push($lista,$);
                    };
                    return $lista;
                }
            
                // **********************
                // UPDATE
                // **********************

                function update($id)
                {
                    $sql = "update acesso set ";
                    $sql .= "id_menu = '".$->getId_menu()."',";

                    $sql .= "where $id = '".$->getPrf_id()."'";
                    return $this->execute($sql);
                }
            }
        ?>