
        <?php
            /*
            *
            * -------------------------------------------------------
            * CLASSNAME:        Diretorio
            * GENERATION DATE:  06.03.2016
            * FOR MYSQL TABLE:  acesso
            * FOR MYSQL DB:     hcb_criancas
            * -------------------------------------------------------
            * CODE GENERATED BY:
            * @MURANO DESIGN
            * -------------------------------------------------------
            *
            */

            session_start();
            $path = $_SESSION['PATH_SYS'];
            include_once($path['DB'].'DataAccess.php');
            include_once($path['DB'].'DAO.php');
            include_once($path['beans'].'Diretorio.php');


            /**
             * Description of DiretorioDAO
             *
             * @author Ana Carolina
             */

            class DiretorioDAO extends DAO{

                public function  __construct() {
                    parent::__construct();
                }

                 
                // **********************
                // INSERT
                // **********************

                public function insertDiretorio($diretorio)
                {
                    $sql =  "insert into acesso ( prf_id,id_menu )values";
                    $sql .= "( '".$diretorio->getPrf_id()."','".$diretorio->getId_menu()."'");
                    return $this->execute($sql);
                }
            
                // **********************
                // DELETE
                // **********************

                public function deleteDiretorio($iddiretorio)
                {
                    $sql = "delete from acesso where drt_id = $iddiretorio";
                    return $this->execute($sql);
                }
            
                // **********************
                // SELECT BY ID
                // **********************

                function selectByIdDiretorio($iddiretorio)
                {
                    $sql = "select * from acesso where drt_id = ". $iddiretorio."limit 1 ";
                    $result = $this->retrieve($sql);
                    $qr = mysql_fetch_array($result);
                    $diretorio= new Diretorio();
                    $diretorio->setPrf_id($qr[prf_id]);
$diretorio->setId_menu($qr[id_menu]);

                    return $diretorio;
                }
            
                // **********************
                // SELECT ALL
                // **********************

                function selectByIdDiretorio($iddiretorio)
                {
                    $sql = "select * from acesso ";
                    $lista = array();
                    $result = $this->retrieve($sql);
                    while ($qr = mysql_fetch_array($result)){
                    $diretorio= new Diretorio();
                    $diretorio->setPrf_id($qr[prf_id]);
$diretorio->setId_menu($qr[id_menu]);

                    array_push($lista,$diretorio);
                    };
                    return $lista;
                }
            
                // **********************
                // UPDATE
                // **********************

                function updateDiretorio($iddiretorio)
                {
                    $sql = "update acesso set ";
                    $sql .= "id_menu = '".$diretorio->getId_menu()."',";

                    $sql .= "where $iddiretorio = '".$diretorio->getPrf_id()."'";
                    return $this->execute($sql);
                }
            }
        ?>