
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Avaliacao
* GENERATION DATE:  28.03.2016
* FOR MYSQL TABLE:  avaliacao
* FOR MYSQL DB:     hcb_criancas_teste
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/
$path = $_SESSION['PATH_SYS'];
include_once($path['DB'].'DataAccess.php');
include_once($path['DB'].'DAO.php');
include_once($path['beans'].'Avaliacao.php');


/**
 * Description of AvaliacaoDAO
 *
 * @author Ana Carolina
 */

class AvaliacaoDAO extends DAO{

    public function  __construct($da) {
        parent::__construct($da);
    }

     
    // **********************
    // INSERT
    // **********************

    public function insertAvaliacao($avaliacao)
    {
        $sql =  "insert into avaliacao ( ava_ano_estudo,ava_tipo_avaliacao,ava_capitulo,ava_exercicio )values";
        $sql .= "( '".$avaliacao->getAva_ano_estudo()."','".$avaliacao->getAva_tipo_avaliacao()."','".$avaliacao->getAva_capitulo()."','".$avaliacao->getAva_exercicio()."')";
        return $this->execute($sql);
    }

    // **********************
    // DELETE
    // **********************

    public function deleteAvaliacao($idavaliacao)
    {
        $sql = "delete from avaliacao where ava_id = $idavaliacao";
        return $this->execute($sql);
    }

    // **********************
    // SELECT BY ID
    // **********************

    function selectByIdAvaliacao($idavaliacao)
    {
        $sql = "select * from avaliacao where ava_id = ". $idavaliacao."limit 1 ";
        $result = $this->retrieve($sql);
        $qr = mysqli_fetch_array($result);
        $avaliacao= new Avaliacao();
        $avaliacao->setAva_id($qr['ava_id']);
        $avaliacao->setAva_ano_estudo($qr['ava_ano_estudo']);
        $avaliacao->setAva_tipo_avaliacao($qr['ava_tipo_avaliacao']);
        $avaliacao->setAva_capitulo($qr['ava_capitulo']);
        $avaliacao->setAva_exercicio($qr['ava_exercicio']);

        return $avaliacao;
    }

    // **********************
    // SELECT ALL
    // **********************

    function selectAllAvaliacao()
    {
        $sql = "select * from avaliacao ";
        $lista = array();
        $result = $this->retrieve($sql);
        while ($qr = mysqli_fetch_array($result)){
            $avaliacao= new Avaliacao();
            $avaliacao->setAva_id($qr['ava_id']);
            $avaliacao->setAva_ano_estudo($qr['ava_ano_estudo']);
            $avaliacao->setAva_tipo_avaliacao($qr['ava_tipo_avaliacao']);
            $avaliacao->setAva_capitulo($qr['ava_capitulo']);
            $avaliacao->setAva_exercicio($qr['ava_exercicio']);

            array_push($lista,$avaliacao);
        };
        return $lista;
    }

    // **********************
    // UPDATE
    // **********************

    function updateAvaliacao($idavaliacao)
    {
        $sql = "update avaliacao set ";
        $sql .= "ava_serie = '".$avaliacao->getAva_ano_estudo()."',";
        $sql .= "ava_tipo_avaliacao = '".$avaliacao->getAva_tipo_avaliacao()."',";
        $sql .= "ava_capitulo = '".$avaliacao->getAva_capitulo()."',";
        $sql .= "ava_exercicio = '".$avaliacao->getAva_exercicio()."',";

        $sql .= "where $idavaliacao = '".$avaliacao->getAva_id()."'";
        return $this->execute($sql);
    }

    function selectAvaliacaoByGeral($idEscola,$idProfessor,$capitulo)
    {
        $sql  = "select av.ava_id,av.ava_serie,av.ava_tipo_avaliacao,av.ava_capitulo,av.ava_exercicio,";
        $sql .= "ex.exe_tipo,ex.exe_serie,exe_ordem,ra.rgc_id,ra.rgc_inicio,rgc_fim,rm.rspm_id,";
        $sql .= "rm.rspm_questao,rspm_resposta,us.usr_id,us.usr_escola,us.usr_perfil,";
        $sql .= "uv.usv_id,uv.usv_serie,uv.usv_grupo,gr.grp_id,gr.grp_professor,gb.gbt_resposta,gb.gbt_questao,gb.gbt_exercicio ";
        $sql .= "from avaliacao av ";
        $sql .= "Inner join exercicio ex on av.ava_exercicio = ex.exe_id ";
        $sql .= "Left Join registro_acesso ra on ra.rgc_exercicio = ex.exe_id and ex.exe_tipo = 1 ";
        $sql .= "Left Join resposta_multipla rm on rm.rspm_exercicio = ex.exe_id and ex.exe_tipo = 2 ";

        $sql .= "Left Join usuario us on (us.usr_id = rm.rspm_usuario or us.usr_id = ra. rgc_usuario) ";

        $sql .= "Left Join usuario_variavel uv on uv.usv_usuario = us.usr_id "; 
        $sql .= "Left Join grupo gr on gr.grp_id = uv.usv_grupo ";
        $sql .= "where us.usr_escola =".$idEscola." ";
        if($idProfessor){
            $sql .= "and gr.grp_professor =".$idProfessor;
        }

        if($capitulo){
             $sql .= " and ex.exe_capitulo =".$capitulo;
        }

       // $sql .= " group by gb.gbt_questao";
        
        echo $sql;
        die();
        $lista = array();
        $result = $this->retrieve($sql);
        while ($qr = mysqli_fetch_array($result)){
            $avaliacao= new Avaliacao();
            $avaliacao->setAva_id($qr['ava_id']);
            $avaliacao->setAva_serie($qr['ava_serie']);
            $avaliacao->setAva_tipo_avaliacao($qr['ava_tipo_avaliacao']);
            $avaliacao->setAva_capitulo($qr['ava_capitulo']);
            $avaliacao->setAva_exercicio($qr['ava_exercicio']);

            array_push($lista,$avaliacao);
        };
        return $lista;
    }
}
?>