
        <?php
            /*
            *
            * -------------------------------------------------------
            * CLASSNAME:        Diretorio
            * GENERATION DATE:  07.03.2016
            * FOR MYSQL TABLE:  diretorio
            * FOR MYSQL DB:     hcb_criancas
            * -------------------------------------------------------
            * CODE GENERATED BY:
            * @MURANO DESIGN
            * -------------------------------------------------------
            *
            */

            session_start();
            $path = $_SESSION['PATH_SYS'];
            include_once($path['DB'].'DataAccess.php');
            include_once($path['DB'].'DAO.php');
            include_once($path['beans'].'Diretorio.php');


            /**
             * Description of DiretorioDAO
             *
             * @author Ana Carolina
             */

            class DiretorioDAO extends DAO{

                public function  __construct() {
                    parent::__construct();
                }

                 
                // **********************
                // INSERT
                // **********************

                public function insertDiretorio($diretorio)
                {
                    $sql =  "insert into diretorio ( drt_nome,drt_descricao )values";
                    $sql .= "( '".$diretorio->getDrt_nome()."','".$diretorio->getDrt_descricao()."'");
                    return $this->execute($sql);
                }
            
                // **********************
                // DELETE
                // **********************

                public function deleteDiretorio($iddiretorio)
                {
                    $sql = "delete from diretorio where drt_id = $iddiretorio";
                    return $this->execute($sql);
                }
            
                // **********************
                // SELECT BY ID
                // **********************

                function selectByIdDiretorio($iddiretorio)
                {
                    $sql = "select * from diretorio where drt_id = ". $iddiretorio."limit 1 ";
                    $result = $this->retrieve($sql);
                    $qr = mysql_fetch_array($result);
                    $diretorio= new Diretorio();
                    $diretorio->setDrt_id($qr[drt_id]);
$diretorio->setDrt_nome($qr[drt_nome]);
$diretorio->setDrt_descricao($qr[drt_descricao]);

                    return $diretorio;
                }
            
                // **********************
                // SELECT ALL
                // **********************

                function selectByIdDiretorio($iddiretorio)
                {
                    $sql = "select * from diretorio ";
                    $lista = array();
                    $result = $this->retrieve($sql);
                    while ($qr = mysql_fetch_array($result)){
                    $diretorio= new Diretorio();
                    $diretorio->setDrt_id($qr[drt_id]);
$diretorio->setDrt_nome($qr[drt_nome]);
$diretorio->setDrt_descricao($qr[drt_descricao]);

                    array_push($lista,$diretorio);
                    };
                    return $lista;
                }
            
                // **********************
                // UPDATE
                // **********************

                function updateDiretorio($iddiretorio)
                {
                    $sql = "update diretorio set ";
                    $sql .= "drt_nome = '".$diretorio->getDrt_nome()."',";
$sql .= "drt_descricao = '".$diretorio->getDrt_descricao()."',";

                    $sql .= "where $iddiretorio = '".$diretorio->getDrt_id()."'";
                    return $this->execute($sql);
                }
            }
        ?>