
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        DocumentoRetorno
* GENERATION DATE:  05.09.2016
* FOR MYSQL TABLE:  documento_retorno
* FOR MYSQL DB:     hcb
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/

session_start();
$path = $_SESSION['PATH_SYS'];
include_once($path['DB'].'DataAccess.php');
include_once($path['DB'].'DAO.php');
include_once($path['beans'].'DocumentoRetorno.php');


/**
 * Description of DocumentoRetornoDAO
 *
 * @author MURANO DESIGN
 */

class DocumentoRetornoDAO extends DAO{

    public function  __construct($da) {
        parent::__construct($da);
    }

     
    // **********************
    // INSERT
    // **********************

    public function insertDocumentoRetorno($documentoretorno)
    {
        $sql =  "insert into documento_retorno ( dor_documento,dor_remetente,dor_envio,dor_visto,dor_rejeitado,dor_data )values";
        $sql .= "( '".$documentoretorno->getDor_documento()."','".$documentoretorno->getDor_remetente()."','".$documentoretorno->getDor_envio()."','".$documentoretorno->getDor_visto()."','".$documentoretorno->getDor_rejeitado()."','".$documentoretorno->getDor_data()."')";
        return $this->execute($sql);
    }

    // **********************
    // DELETE
    // **********************

    public function deleteDocumentoRetorno($iddocumentoretorno)
    {
        $sql = "delete from documento_retorno where dor_id = $iddocumentoretorno";
        return $this->execute($sql);
    }

    // **********************
    // SELECT BY ID
    // **********************

    function selectByIdDocumentoRetorno($iddocumentoretorno)
    {
        $sql = "select * from documento_retorno where dor_id = ". $iddocumentoretorno."limit 1 ";
        $result = $this->retrieve($sql);
        $qr = mysqli_fetch_array($result);
        $documentoretorno= new DocumentoRetorno();
        $documentoretorno->setDor_id($qr['dor_id']);
$documentoretorno->setDor_documento($qr['dor_documento']);
$documentoretorno->setDor_remetente($qr['dor_remetente']);
$documentoretorno->setDor_envio($qr['dor_envio']);
$documentoretorno->setDor_visto($qr['dor_visto']);
$documentoretorno->setDor_rejeitado($qr['dor_rejeitado']);
$documentoretorno->setDor_data($qr['dor_data']);

        return $documentoretorno;
    }

    // **********************
    // SELECT ALL
    // **********************

    function  selectAllDocumentoRetorno()
    {
        $sql = "select * from documento_retorno ";
        $lista = array();
        $result = $this->retrieve($sql);
        while ($qr = mysqli_fetch_array($result)){
        $documentoretorno= new DocumentoRetorno();
        $documentoretorno->setDor_id($qr['dor_id']);
$documentoretorno->setDor_documento($qr['dor_documento']);
$documentoretorno->setDor_remetente($qr['dor_remetente']);
$documentoretorno->setDor_envio($qr['dor_envio']);
$documentoretorno->setDor_visto($qr['dor_visto']);
$documentoretorno->setDor_rejeitado($qr['dor_rejeitado']);
$documentoretorno->setDor_data($qr['dor_data']);

        array_push($lista,$documentoretorno);
        };
        return $lista;
    }

    // **********************
    // UPDATE
    // **********************

    function updateDocumentoRetorno($documentoretorno)
    {
        $sql = "update documento_retorno set ";
        $sql .= "dor_documento = '".$documentoretorno->getDor_documento()."',";
$sql .= "dor_remetente = '".$documentoretorno->getDor_remetente()."',";
$sql .= "dor_envio = '".$documentoretorno->getDor_envio()."',";
$sql .= "dor_visto = '".$documentoretorno->getDor_visto()."',";
$sql .= "dor_rejeitado = '".$documentoretorno->getDor_rejeitado()."',";
$sql .= "dor_data = '".$documentoretorno->getDor_data()."',";

        $sql .= "where dor_id = '".$documentoretorno->getDor_id()."'";
        return $this->execute($sql);
    }
}
?>