
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Documentos
* GENERATION DATE:  05.09.2016
* FOR MYSQL TABLE:  documento
* FOR MYSQL DB:     hcb
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/

session_start();
$path = $_SESSION['PATH_SYS'];
include_once($path['DB'].'DataAccess.php');
include_once($path['DB'].'DAO.php');
include_once($path['beans'].'Documento.php');


/**
 * Description of DocumentosDAO
 *
 * @author MURANO DESIGN
 */

class DocumentoDAO extends DAO{

    public function  __construct($da) {
        parent::__construct($da);
    }

     
    // **********************
    // INSERT
    // **********************

    public function insertDocumentos($documentos)
    {
        $sql =  "insert into documento ( doc_assunto,doc_descricao,doc_arquivo )values";
        $sql .= "( '".$documentos->getDoc_assunto()."','".$documentos->getDoc_descricao()."','".$documentos->getDoc_arquivo()."')";
        return $this->execute($sql);
    }

    // **********************
    // DELETE
    // **********************

    public function deleteDocumentos($iddocumentos)
    {
        $sql = "delete from documento where doc_id = $iddocumentos";
        return $this->execute($sql);
    }

    // **********************
    // SELECT BY ID
    // **********************

    function selectByIdDocumentos($iddocumentos)
    {
        $sql = "select * from documento where doc_id = ". $iddocumentos."limit 1 ";
        $result = $this->retrieve($sql);
        $qr = mysqli_fetch_array($result);
        $documentos= new Documentos();
        $documentos->setDoc_id($qr['doc_id']);
$documentos->setDoc_assunto($qr['doc_assunto']);
$documentos->setDoc_descricao($qr['doc_descricao']);
$documentos->setDoc_arquivo($qr['doc_arquivo']);

        return $documentos;
    }

    // **********************
    // SELECT ALL
    // **********************

    function  selectAllDocumentos()
    {
        $sql = "select * from documento ";
        $lista = array();
        $result = $this->retrieve($sql);
        while ($qr = mysqli_fetch_array($result)){
        $documentos= new Documentos();
        $documentos->setDoc_id($qr['doc_id']);
$documentos->setDoc_assunto($qr['doc_assunto']);
$documentos->setDoc_descricao($qr['doc_descricao']);
$documentos->setDoc_arquivo($qr['doc_arquivo']);

        array_push($lista,$documentos);
        };
        return $lista;
    }

    // **********************
    // UPDATE
    // **********************

    function updateDocumentos($documentos)
    {
        $sql = "update documento set ";
        $sql .= "doc_assunto = '".$documentos->getDoc_assunto()."',";
$sql .= "doc_descricao = '".$documentos->getDoc_descricao()."',";
$sql .= "doc_arquivo = '".$documentos->getDoc_arquivo()."',";

        $sql .= "where doc_id = '".$documentos->getDoc_id()."'";
        return $this->execute($sql);
    }
}
?>