<?php
    /*
    *
    * -------------------------------------------------------
    * CLASSNAME:        PeriodoDAO
    * GENERATION DATE:  14.04.2016
    * FOR MYSQL TABLE:  periodo
    * FOR MYSQL DB:     hcb_criancas_teste
    * -------------------------------------------------------
    * CODE GENERATED BY:
    * @MURANO DESIGN
    * -------------------------------------------------------
    *
    */

    $path = $_SESSION['PATH_SYS'];
    include_once($path['DB'].'DataAccess.php');
    include_once($path['DB'].'DAO.php');
    include_once($path['beans'].'Periodo.php');
    include_once($path['funcao'].'DatasFuncao.php');


    /**
     * Description of PeriodoDAO
     *
     * @author Ana Carolina
     */

    class PeriodoDAO extends DAO{

        public function  __construct($da)
        {
            parent::__construct($da);
        }

         
        // **********************
        // INSERT
        // **********************

        public function insert($periododao)
        {
            $sql =  "insert into periodo ( prd_periodo )values";
            $sql .= "( '".$periododao->getPrd_periodo()."')";
            return $this->execute($sql);
        }
    
        // **********************
        // DELETE
        // **********************

        public function delete($idperiododao)
        {
            $sql = "delete from periodo where prd_id = $idperiododao";
            return $this->execute($sql);
        }
    
        // **********************
        // SELECT BY ID
        // **********************

        function selectById($idperiododao)
        {
            $sql = "select * from periodo where prd_id = ". $idperiododao." limit 1 ";
            $result = $this->retrieve($sql);
                $qr = mysqli_fetch_array($result);
                $periododao= new Periodo();
                $periododao->setPrd_id($qr['prd_id']);
                $periododao->setPrd_periodo($qr['prd_periodo']);

            return $periododao;
        }
    
        // **********************
        // SELECT ALL
        // **********************

        function selectAll()
        {
            $sql = "select * from periodo ";
            $lista = array();
            $result = $this->retrieve($sql);
            while ($qr = mysqli_fetch_array($result)){
                $periododao = new Periodo();
                $periododao->setPrd_id($qr['prd_id']);
                $periododao->setPrd_periodo($qr['prd_periodo']);

                array_push($lista,$periododao);
            };
            return $lista;
        }
    
        // **********************
        // UPDATE
        // **********************

        function update($idperiododao)
        {
            $sql = "update periodo set ";
            $sql .= "prd_periodo = '".$periododao->getPrd_periodo()."',";

            $sql .= "where $idperiododao = '".$periododao->getPrd_id()."'";
            return $this->execute($sql);
        }

        public function listarDisponiveisProfessorSerieSemGrupo($serie, $idProfessor)
        {
            $sql = "SELECT * FROM periodo p WHERE
                        p.prd_id NOT IN (
                            SELECT p2.prd_id FROM periodo p2
                            JOIN grupo g ON g.grp_periodo = p2.prd_id
                            WHERE g.grp_professor = ".$idProfessor." AND g.grp_serie = ".$serie.")";
            $result = $this->retrieve($sql);
            $lista = array();
            while ($qr = mysqli_fetch_array($result))
            {
                $per = new Periodo();
                $per->setPrd_id($qr["prd_id"]);
                $per->setPrd_periodo($qr["prd_periodo"]);
                array_push($lista, $per);   
            }
            return $lista;
        }

        public function listarDisponiveisProfessorSerie($serie, $idProfessor)
        {
            $sql = "SELECT * FROM periodo p
                        JOIN grupo g ON g.grp_periodo = p.prd_id
                        WHERE g.grp_professor = ".$idProfessor." AND g.grp_serie = ".$serie;
            $result = $this->retrieve($sql);
            $lista = array();
            while ($qr = mysqli_fetch_array($result))
            {
                $per = new Periodo();
                $per->setPrd_id($qr["prd_id"]);
                $per->setPrd_periodo($qr["prd_periodo"]);
                array_push($lista, $per);   
            }
            return $lista;
        }
    }
?>