
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Administracao
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  administracao
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Administracao
{ 
private $adm_id;

private $adm_administracao;



public function Administracao()
{

}




public function getadm_id()
{
return $this->adm_id;
}

public function getadm_administracao()
{
return $this->adm_administracao;
}



public function setadm_id($val)
{
$this->adm_id =  $val;
}

public function setadm_administracao($val)
{
$this->adm_administracao =  $val;
}


} 

?>