
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Administracao
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  administracao
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Administracao
{ 
private $dmn_id;

private $dmn_administracao;



public function Administracao()
{

}




public function getDmn_id()
{
return $this->dmn_id;
}

public function getDmn_administracao()
{
return $this->dmn_administracao;
}



public function setDmn_id($val)
{
$this->dmn_id =  $val;
}

public function setDmn_administracao($val)
{
$this->dmn_administracao =  $val;
}


} 

?>

