
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        AnoLetivo
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  ano_letivo
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class AnoLetivo
{ 
private $ano_id;

private $ano;



public function AnoLetivo()
{

}




public function getNlt_id()
{
return $this->ano_id;
}

public function getAno()
{
return $this->ano;
}



public function setNlt_id($val)
{
$this->$ano_id =  $val;
}

public function setAno($val)
{
$this->ano =  $val;
}


} 

?>

