
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        AnoLetivo
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  ano_letivo
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class AnoLetivo
{ 
private $ano_id;

private $ano_ano;



public function AnoLetivo()
{

}




public function getAno_id()
{
return $this->ano_id;
}

public function getAno_ano()
{
return $this->ano_ano;
}



public function setAno_id($val)
{
$this->ano_id =  $val;
}

public function setAno_ano($val)
{
$this->ano_ano =  $val;
}


} 

?>

