
        <?php
        /*
        *
        * -------------------------------------------------------
        * CLASSNAME:        Avaliacao
        * GENERATION DATE:  28.03.2016
        * FOR MYSQL TABLE:  avaliacao
        * FOR MYSQL DB:     hcb_criancas_teste
        * -------------------------------------------------------
        * CODE GENERATED BY:
        * @MURANO DESIGN
        * -------------------------------------------------------
        *
        */

        class Avaliacao
        {
        private $ava_id;
    
            private $ava_serie;
            private $ava_tipo_avaliacao;
            private $ava_capitulo;
            private $ava_exercicio;
        

    public function Avaliacao()
    {

    }
    

    
        public function getAva_id()
        {
        return $this->ava_id;
        }
        
        public function getAva_serie()
        {
        return $this->ava_ano_estudo;
        }
        
        public function getAva_tipo_avaliacao()
        {
        return $this->ava_tipo_avaliacao;
        }
        
        public function getAva_capitulo()
        {
        return $this->ava_capitulo;
        }
        
        public function getAva_exercicio()
        {
        return $this->ava_exercicio;
        }
        

    
        public function setAva_id($val)
        {
            $this->ava_id =  $val;
        }
    
        public function setAva_serie($val)
        {
            $this->ava_ano_estudo =  $val;
        }
    
        public function setAva_tipo_avaliacao($val)
        {
            $this->ava_tipo_avaliacao =  $val;
        }
    
        public function setAva_capitulo($val)
        {
            $this->ava_capitulo =  $val;
        }
    
        public function setAva_exercicio($val)
        {
            $this->ava_exercicio =  $val;
        }
    
    }

    ?>

    