
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Calendario
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  calendario
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Calendario
{ 
private $cld_id;

private $cld_data_inicio;
private $cld_data_fim;
private $cld_evento;
private $cld_ano_letivo;
private $cld_tipo_evento;
private $cld_descricao;
private $cld_imagem;
private $cld_hora_inicio;
private $cld_hora_fim;
private $cld_visivel;



public function Calendario()
{

}




public function getCld_id()
{
return $this->cld_id;
}

public function getCld_data_inicio()
{
return $this->cld_data_inicio;
}

public function getCld_data_fim()
{
return $this->cld_data_fim;
}

public function getCld_evento()
{
return $this->cld_evento;
}

public function getCld_ano_letivo()
{
return $this->cld_ano_letivo;
}

public function getCld_tipo_evento()
{
return $this->cld_tipo_evento;
}

public function getCld_descricao()
{
return $this->cld_descricao;
}

public function getCld_imagem()
{
return $this->cld_imagem;
}

public function getCld_hora_inicio()
{
return $this->cld_hora_inicio;
}

public function getCld_hora_fim()
{
return $this->cld_hora_fim;
}

public function getCld_visivel()
{
return $this->cld_visivel;
}



public function setCld_id($val)
{
$this->cld_id =  $val;
}

public function setCld_data_inicio($val)
{
$this->cld_data_inicio =  $val;
}

public function setCld_data_fim($val)
{
$this->cld_data_fim =  $val;
}

public function setCld_evento($val)
{
$this->cld_evento =  $val;
}

public function setCld_ano_letivo($val)
{
$this->cld_ano_letivo =  $val;
}

public function setCld_tipo_evento($val)
{
$this->cld_tipo_evento =  $val;
}

public function setCld_descricao($val)
{
$this->cld_descricao =  $val;
}

public function setCld_imagem($val)
{
$this->cld_imagem =  $val;
}

public function setCld_hora_inicio($val)
{
$this->cld_hora_inicio =  $val;
}

public function setCld_hora_fim($val)
{
$this->cld_hora_fim =  $val;
}

public function setCld_visivel($val)
{
$this->cld_visivel =  $val;
}


} 

?>

