
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Capitulo
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  capitulo
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Capitulo
{ 
private $cpt_id;

private $cpt_capitulo;



public function Capitulo()
{

}




public function getCpt_id()
{
return $this->cpt_id;
}

public function getCpt_capitulo()
{
return $this->cpt_capitulo;
}



public function setCpt_id($val)
{
$this->cpt_id =  $val;
}

public function setCpt_capitulo($val)
{
$this->cpt_capitulo =  $val;
}


} 

?>

