<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        CategoriaGaleria
* GENERATION DATE:  11.03.2016
* FOR MYSQL TABLE:  categoria_galeria
* FOR MYSQL DB:     casar
* -------------------------------------------------------
* CODE GENERATED BY:
* @Lombardi
* -------------------------------------------------------
*
*/

class CategoriaGaleria
{
	private $ctg_id;
	private $ctg_categoria;
	private $ctg_classe;

	public function CategoriaGaleria()
	{

	}

	public function getCtg_id()
	{
		return $this->ctg_id;
	}

	public function getCtg_categoria()
	{
		return $this->ctg_categoria;
	}

	public function getCtg_classe()
	{
		return $this->ctg_classe;
	}


	public function setCtg_id($val)
	{
		$this->ctg_id = $val;
	}

	public function setCtg_categoria($val)
	{
		$this->ctg_categoria = $val;
	}

	public function setCtg_classe($val)
	{
		$this->ctg_classe = $val;
	}

}

?>