
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        CategoriaFuncional
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  categoria_funcional
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class CategoriaFuncional
{ 
private $ctf_id;

private $ctf_categoria;



public function CategoriaFuncional()
{

}




public function getCtf_id()
{
return $this->ctf_id;
}

public function getCtf_categoria()
{
return $this->ctf_categoria;
}



public function setCtf_id($val)
{
$this->ctf_id =  $val;
}

public function setCtf_categoria($val)
{
$this->ctf_categoria =  $val;
}


} 

?>

