<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Categoria_Galeria
* GENERATION DATE:  11.03.2016
* FOR MYSQL TABLE:  categoria_galeria
* FOR MYSQL DB:     casar
* -------------------------------------------------------
* CODE GENERATED BY:
* @Lombardi
* -------------------------------------------------------
*
*/

class Categoria_Galeria
{
	private $ctg_id;
	private $ctg_galeria;

	public function Categoria_Galeria()
	{

	}

	public function getCtg_id()
	{
		return $this->ctg_id;
	}

	public function getCtg_categoria()
	{
		return $this->ctg_categoria;
	}


	public function setCtg_id($val)
	{
		$this->ctg_id = $val;
	}

	public function setCtg_categoria($val)
	{
		$this->ctg_categoria = $val;
	}

}

?>