
        <?php
        /*
        *
        * -------------------------------------------------------
        * CLASSNAME:        Diretorio
        * GENERATION DATE:  07.03.2016
        * FOR MYSQL TABLE:  diretorio
        * FOR MYSQL DB:     hcb_criancas
        * -------------------------------------------------------
        * CODE GENERATED BY:
        * @MURANO DESIGN
        * -------------------------------------------------------
        *
        */

        class Diretorio
        {
        private $drt_id;
    
            private $drt_nome;
            private $drt_descricao;
        

    public function Diretorio()
    {

    }
    

    
        public function getDrt_id()
        {
            return $this->drt_id;
        }
        
        public function getDrt_nome()
        {
            return $this->drt_nome;
        }
        
        public function getDrt_descricao()
        {
            return $this->drt_descricao;
        }
        

    
        public function setDrt_id($val)
        {
            $this->drt_id =  $val;
        }
    
        public function setDrt_nome($val)
        {
            $this->drt_nome =  $val;
        }
    
        public function setDrt_descricao($val)
        {
            $this->drt_descricao =  $val;
        }
    
    }

    ?>

    