
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Email
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  email
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Email
{ 
private $ml_id;

private $ml_usuario;
private $ml_tipo_email;
private $ml_identificacao_email;



public function Email()
{

}




public function getMl_id()
{
return $this->ml_id;
}

public function getMl_usuario()
{
return $this->ml_usuario;
}

public function getMl_tipo_email()
{
return $this->ml_tipo_email;
}

public function getMl_identificacao_email()
{
return $this->ml_identificacao_email;
}



public function setMl_id($val)
{
$this->ml_id =  $val;
}

public function setMl_usuario($val)
{
$this->ml_usuario =  $val;
}

public function setMl_tipo_email($val)
{
$this->ml_tipo_email =  $val;
}

public function setMl_identificacao_email($val)
{
$this->ml_identificacao_email =  $val;
}


} 

?>

