<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Endereco
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  endereco
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Endereco
{ 
private $end_id;

private $end_logradouro;
private $end_numero;
private $end_complemento;
private $end_cep;
private $end_cidade;
private $end_uf;
private $end_pais;
private $end_telefone_residencial;
private $end_telefone_comercial;
private $end_telefone_celular;
private $end_email;



public function Endereco()
{

}




public function getend_id()
{
return $this->end_id;
}

public function getend_logradouro()
{
return $this->end_logradouro;
}

public function getend_numero()
{
return $this->end_numero;
}

public function getend_complemento()
{
return $this->end_complemento;
}

public function getend_cep()
{
return $this->end_cep;
}

public function getend_cidade()
{
return $this->end_cidade;
}

public function getend_uf()
{
return $this->end_uf;
}

public function getend_pais()
{
return $this->end_pais;
}

public function getend_telefone_residencial()
{
return $this->end_telefone_residencial;
}

public function getend_telefone_comercial()
{
return $this->end_telefone_comercial;
}

public function getend_telefone_celular()
{
return $this->end_telefone_celular;
}

public function getend_email()
{
return $this->end_email;
}



public function setend_id($val)
{
$this->end_id =  $val;
}

public function setend_logradouro($val)
{
$this->end_logradouro =  $val;
}

public function setend_numero($val)
{
$this->end_numero =  $val;
}

public function setend_complemento($val)
{
$this->end_complemento =  $val;
}

public function setend_cep($val)
{
$this->end_cep =  $val;
}

public function setend_cidade($val)
{
$this->end_cidade =  $val;
}

public function setend_uf($val)
{
$this->end_uf =  $val;
}

public function setend_pais($val)
{
$this->end_pais =  $val;
}

public function setend_telefone_residencial($val)
{
$this->end_telefone_residencial =  $val;
}

public function setend_telefone_comercial($val)
{
$this->end_telefone_comercial =  $val;
}

public function setend_telefone_celular($val)
{
$this->end_telefone_celular =  $val;
}

public function setend_email($val)
{
$this->end_email =  $val;
}


} 

?>