
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Endereco
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  endereco
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Endereco
{ 
private $ndr_id;

private $ndr_logradouro;
private $ndr_numero;
private $ndr_complemento;
private $ndr_cep;
private $ndr_cidade;
private $ndr_uf;
private $ndr_pais;
private $ndr_telefone_residencial;
private $ndr_telefone_comercial;
private $ndr_telefone_celular;
private $ndr_email;



public function Endereco()
{

}




public function getNdr_id()
{
return $this->ndr_id;
}

public function getNdr_logradouro()
{
return $this->ndr_logradouro;
}

public function getNdr_numero()
{
return $this->ndr_numero;
}

public function getNdr_complemento()
{
return $this->ndr_complemento;
}

public function getNdr_cep()
{
return $this->ndr_cep;
}

public function getNdr_cidade()
{
return $this->ndr_cidade;
}

public function getNdr_uf()
{
return $this->ndr_uf;
}

public function getNdr_pais()
{
return $this->ndr_pais;
}

public function getNdr_telefone_residencial()
{
return $this->ndr_telefone_residencial;
}

public function getNdr_telefone_comercial()
{
return $this->ndr_telefone_comercial;
}

public function getNdr_telefone_celular()
{
return $this->ndr_telefone_celular;
}

public function getNdr_email()
{
return $this->ndr_email;
}



public function setNdr_id($val)
{
$this->ndr_id =  $val;
}

public function setNdr_logradouro($val)
{
$this->ndr_logradouro =  $val;
}

public function setNdr_numero($val)
{
$this->ndr_numero =  $val;
}

public function setNdr_complemento($val)
{
$this->ndr_complemento =  $val;
}

public function setNdr_cep($val)
{
$this->ndr_cep =  $val;
}

public function setNdr_cidade($val)
{
$this->ndr_cidade =  $val;
}

public function setNdr_uf($val)
{
$this->ndr_uf =  $val;
}

public function setNdr_pais($val)
{
$this->ndr_pais =  $val;
}

public function setNdr_telefone_residencial($val)
{
$this->ndr_telefone_residencial =  $val;
}

public function setNdr_telefone_comercial($val)
{
$this->ndr_telefone_comercial =  $val;
}

public function setNdr_telefone_celular($val)
{
$this->ndr_telefone_celular =  $val;
}

public function setNdr_email($val)
{
$this->ndr_email =  $val;
}


} 

?>

