
	<?php
			/*
			*
			* -------------------------------------------------------
			* CLASSNAME:        Escola
			* GENERATION DATE:  11.06.2015
			* FOR MYSQL TABLE:  escola
			* FOR MYSQL DB:     hcb_criancas
			* -------------------------------------------------------
			* CODE GENERATED BY:
			* @MURANO DESIGN
			* -------------------------------------------------------
			*
			*/



			class Escola
			{ 
			private $esc_id;

			private $esc_razao_social;
			private $esc_cnpj;
			private $esc_endereco;
			private $esc_tipo_escola;
			private $esc_administracao;



			public function Escola()
			{

			}




			public function getesc_id()
			{
			return $this->esc_id;
			}

			public function getesc_razao_social()
			{
			return $this->esc_razao_social;
			}

			public function getesc_cnpj()
			{
			return $this->esc_cnpj;
			}

			public function getesc_endereco()
			{
			return $this->esc_endereco;
			}

			public function getesc_tipo_escola()
			{
			return $this->esc_tipo_escola;
			}

			public function getesc_administracao()
			{
			return $this->esc_administracao;
			}



			public function setesc_id($val)
			{
			$this->esc_id =  $val;
			}

			public function setesc_razao_social($val)
			{
			$this->esc_razao_social =  $val;
			}

			public function setesc_cnpj($val)
			{
			$this->esc_cnpj =  $val;
			}

			public function setesc_endereco($val)
			{
			$this->esc_endereco =  $val;
			}

			public function setesc_tipo_escola($val)
			{
			$this->esc_tipo_escola =  $val;
			}

			public function setesc_administracao($val)
			{
			$this->esc_administracao =  $val;
			}


			} 

			?>

