
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Escola
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  escola
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Escola
{ 
private $scl_id;

private $scl_razao_social;
private $scl_cnpj;
private $scl_endereco;
private $scl_tipo_escola;
private $scl_administracao;



public function Escola()
{

}




public function getScl_id()
{
return $this->scl_id;
}

public function getScl_razao_social()
{
return $this->scl_razao_social;
}

public function getScl_cnpj()
{
return $this->scl_cnpj;
}

public function getScl_endereco()
{
return $this->scl_endereco;
}

public function getScl_tipo_escola()
{
return $this->scl_tipo_escola;
}

public function getScl_administracao()
{
return $this->scl_administracao;
}



public function setScl_id($val)
{
$this->scl_id =  $val;
}

public function setScl_razao_social($val)
{
$this->scl_razao_social =  $val;
}

public function setScl_cnpj($val)
{
$this->scl_cnpj =  $val;
}

public function setScl_endereco($val)
{
$this->scl_endereco =  $val;
}

public function setScl_tipo_escola($val)
{
$this->scl_tipo_escola =  $val;
}

public function setScl_administracao($val)
{
$this->scl_administracao =  $val;
}


} 

?>

