
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Escola
* GENERATION DATE:  08.03.2016
* FOR MYSQL TABLE:  escola
* FOR MYSQL DB:     casar
* -------------------------------------------------------
* CODE GENERATED BY:
* @Lombardi
* -------------------------------------------------------
*
*/



class Escola
{ 
private $esc_id;

private $esc_razao_social;
private $esc_nome;
private $esc_cnpj;
private $esc_endereco;
private $esc_tipo_escola;
private $esc_administracao;
private $esc_status;
private $esc_site;
private $esc_nome_diretor;
private $esc_email_diretor;
private $esc_nome_coordenador;
private $esc_email_coordenador;
private $esc_codigo;



public function Escola()
{

}




public function getEsc_id()
{
return $this->esc_id;
}

public function getEsc_razao_social()
{
return $this->esc_razao_social;
}

public function getEsc_nome()
{
return $this->esc_nome;
}

public function getEsc_cnpj()
{
return $this->esc_cnpj;
}

public function getEsc_endereco()
{
return $this->esc_endereco;
}

public function getEsc_tipo_escola()
{
return $this->esc_tipo_escola;
}

public function getEsc_administracao()
{
return $this->esc_administracao;
}

public function getEsc_status()
{
return $this->esc_status;
}

public function getEsc_site()
{
return $this->esc_site;
}

public function getEsc_nome_diretor()
{
return $this->esc_nome_diretor;
}

public function getEsc_email_diretor()
{
return $this->esc_email_diretor;
}

public function getEsc_nome_coordenador()
{
return $this->esc_nome_coordenador;
}

public function getEsc_email_coordenador()
{
return $this->esc_email_coordenador;
}

public function getEsc_codigo()
{
return $this->esc_codigo;
}



public function setEsc_id($val)
{
$this->esc_id =  $val;
}

public function setEsc_razao_social($val)
{
$this->esc_razao_social =  $val;
}

public function setEsc_nome($val)
{
$this->esc_nome =  $val;
}

public function setEsc_cnpj($val)
{
$this->esc_cnpj =  $val;
}

public function setEsc_endereco($val)
{
$this->esc_endereco =  $val;
}

public function setEsc_tipo_escola($val)
{
$this->esc_tipo_escola =  $val;
}

public function setEsc_administracao($val)
{
$this->esc_administracao =  $val;
}

public function setEsc_status($val)
{
$this->esc_status =  $val;
}

public function setEsc_site($val)
{
$this->esc_site =  $val;
}

public function setEsc_nome_diretor($val)
{
$this->esc_nome_diretor =  $val;
}

public function setEsc_email_diretor($val)
{
$this->esc_email_diretor =  $val;
}

public function setEsc_nome_coordenador($val)
{
$this->esc_nome_coordenador =  $val;
}

public function setEsc_email_coordenador($val)
{
$this->esc_email_coordenador =  $val;
}

public function setEsc_codigo($val)
{
$this->esc_codigo =  $val;
}


} 

?>

