
        <?php
        /*
        *
        * -------------------------------------------------------
        * CLASSNAME:        Exercicio
        * GENERATION DATE:  07.03.2016
        * FOR MYSQL TABLE:  exercicio
        * FOR MYSQL DB:     hcb_criancas
        * -------------------------------------------------------
        * CODE GENERATED BY:
        * @MURANO DESIGN
        * -------------------------------------------------------
        *
        */

        class Exercicio
        {
        private $exe_id;
    
            private $exe_nome;
            private $exe_diretorio;
            private $exe_tipo;
            private $exe_serie;
            private $exe_tema;
            private $exe_capitulo;
            private $exe_ordem;
        

    public function Exercicio()
    {

    }
    

    
        public function getExe_id()
        {
        return $this->exe_id;
        }
        
        public function getExe_nome()
        {
        return $this->exe_nome;
        }
        
        public function getExe_diretorio()
        {
        return $this->exe_diretorio;
        }
        
        public function getExe_tipo()
        {
        return $this->exe_tipo;
        }
        
        public function getExe_serie()
        {
        return $this->exe_serie;
        }
        
        public function getExe_tema()
        {
        return $this->exe_tema;
        }
        
        public function getExe_capitulo()
        {
        return $this->exe_capitulo;
        }
        
        public function getExe_ordem()
        {
        return $this->exe_ordem;
        }
        

    
        public function setExe_id($val)
        {
            $this->exe_id =  $val;
        }
    
        public function setExe_nome($val)
        {
            $this->exe_nome =  $val;
        }
    
        public function setExe_diretorio($val)
        {
            $this->exe_diretorio =  $val;
        }
    
        public function setExe_tipo($val)
        {
            $this->exe_tipo =  $val;
        }
    
        public function setExe_serie($val)
        {
            $this->exe_serie =  $val;
        }
    
        public function setExe_tema($val)
        {
            $this->exe_tema =  $val;
        }
    
        public function setExe_capitulo($val)
        {
            $this->exe_capitulo =  $val;
        }
    
        public function setExe_ordem($val)
        {
            $this->exe_ordem =  $val;
        }
    
    }

    ?>

    