
<?php
			/*
			*
			* -------------------------------------------------------
			* CLASSNAME:        Exercicio
			* GENERATION DATE:  11.06.2015
			* FOR MYSQL TABLE:  exercicio
			* FOR MYSQL DB:     hcb_criancas
			* -------------------------------------------------------
			* CODE GENERATED BY:
			* @MURANO DESIGN
			* -------------------------------------------------------
			*
			*/



			class Exercicio
			{ 
			private $exe_id;

			private $exe_tipo;
			private $exe_serie;
			private $exe_tema;
			private $exe_capitulo;



			public function Exercicio()
			{

			}




			public function getexe_id()
			{
			return $this->exe_id;
			}

			public function getexe_tipo()
			{
			return $this->exe_tipo;
			}

			public function getexe_serie()
			{
			return $this->exe_serie;
			}

			public function getexe_tema()
			{
			return $this->exe_tema;
			}

			public function getexe_capitulo()
			{
			return $this->exe_capitulo;
			}



			public function setexe_id($val)
			{
			$this->exe_id =  $val;
			}

			public function setexe_tipo($val)
			{
			$this->exe_tipo =  $val;
			}

			public function setexe_serie($val)
			{
			$this->exe_serie =  $val;
			}

			public function setexe_tema($val)
			{
			$this->exe_tema =  $val;
			}

			public function setexe_capitulo($val)
			{
			$this->exe_capitulo =  $val;
			}


			} 

			?>

