
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Exercicio
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  exercicio
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Exercicio
{ 
private $xrc_id;

private $xrc_tipo;
private $xrc_serie;
private $xrc_tema;
private $xrc_capitulo;



public function Exercicio()
{

}




public function getXrc_id()
{
return $this->xrc_id;
}

public function getXrc_tipo()
{
return $this->xrc_tipo;
}

public function getXrc_serie()
{
return $this->xrc_serie;
}

public function getXrc_tema()
{
return $this->xrc_tema;
}

public function getXrc_capitulo()
{
return $this->xrc_capitulo;
}



public function setXrc_id($val)
{
$this->xrc_id =  $val;
}

public function setXrc_tipo($val)
{
$this->xrc_tipo =  $val;
}

public function setXrc_serie($val)
{
$this->xrc_serie =  $val;
}

public function setXrc_tema($val)
{
$this->xrc_tema =  $val;
}

public function setXrc_capitulo($val)
{
$this->xrc_capitulo =  $val;
}


} 

?>

