
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ForumView
* GENERATION DATE:  13.08.2015
* FOR MYSQL TABLE:  forum_views
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @Ewerton Donizet
* -------------------------------------------------------
*
*/



class ForumView
{ 
private $frv_id;

private $frv_questao;
private $frv_usuario;
private $frv_data;



public function ForumView()
{

}




public function getFrv_id()
{
return $this->frv_id;
}

public function getFrv_questao()
{
return $this->frv_questao;
}

public function getFrv_usuario()
{
return $this->frv_usuario;
}

public function getFrv_data()
{
return $this->frv_data;
}



public function setFrv_id($val)
{
$this->frv_id =  $val;
}

public function setFrv_questao($val)
{
$this->frv_questao =  $val;
}

public function setFrv_usuario($val)
{
$this->frv_usuario =  $val;
}

public function setFrv_data($val)
{
$this->frv_data =  $val;
}


} 

?>

