
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ForumQuestao
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  forum_questao
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class ForumQuestao
{ 
private $frq_id;

private $frq_usuario;
private $frq_questao;
private $frq_anexo;
private $frq_data;
private $frq_topico;



public function ForumQuestao()
{

}




public function getFrq_id()
{
return $this->frq_id;
}

public function getFrq_usuario()
{
return $this->frq_usuario;
}

public function getFrq_questao()
{
return $this->frq_questao;
}

public function getFrq_anexo()
{
return $this->frq_anexo;
}

public function getFrq_data()
{
return $this->frq_data;
}

public function getFrq_topico()
{
return $this->frq_topico;
}



public function setFrq_id($val)
{
$this->frq_id =  $val;
}

public function setFrq_usuario($val)
{
$this->frq_usuario =  $val;
}

public function setFrq_questao($val)
{
$this->frq_questao =  $val;
}

public function setFrq_anexo($val)
{
$this->frq_anexo =  $val;
}

public function setFrq_data($val)
{
$this->frq_data =  $val;
}

public function setFrq_topico($val)
{
$this->frq_topico =  $val;
}


} 

?>

