<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ForumQuestaoParticipante
* GENERATION DATE:  27.04.2016
* FOR MYSQL TABLE:  forum_questao_participante
* FOR MYSQL DB:     hcb_criancas_teste
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/

class ForumQuestaoParticipante
{
    private $fqp_questao;
    private $fqp_usuario;
    private $fqp_ultima_visualizacao;
        

    public function ForumQuestaoParticipante()
    {
        //Construtor vazio
    }

    public function getFqp_questao()
    {
        return $this->fqp_questao;
    }

    public function getFqp_usuario()
    {
        return $this->fqp_usuario;
    }

    public function getFqp_ultima_visualizacao()
    {
        return $this->fqp_ultima_visualizacao;
    }



    public function setFqp_questao($val)
    {
        $this->fqp_questao = $val;
    }

    public function setFqp_usuario($val)
    {
        $this->fqp_usuario = $val;
    }

    public function setFqp_ultima_visualizacao($val)
    {
        $this->fqp_ultima_visualizacao = $val;
    }
}
?>

    