
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ForumResposta
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  forum_resposta
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class ForumResposta
{ 
private $frr_id;

private $frr_usuario;
private $frr_resposta;
private $frr_questao;
private $frr_anexo;
private $frr_data;



public function ForumResposta()
{

}




public function getFrr_id()
{
return $this->frr_id;
}

public function getFrr_usuario()
{
return $this->frr_usuario;
}

public function getFrr_resposta()
{
return $this->frr_resposta;
}

public function getFrr_questao()
{
return $this->frr_questao;
}

public function getFrr_anexo()
{
return $this->frr_anexo;
}

public function getFrr_data()
{
return $this->frr_data;
}



public function setFrr_id($val)
{
$this->frr_id =  $val;
}

public function setFrr_usuario($val)
{
$this->frr_usuario =  $val;
}

public function setFrr_resposta($val)
{
$this->frr_resposta =  $val;
}

public function setFrr_questao($val)
{
$this->frr_questao =  $val;
}

public function setFrr_anexo($val)
{
$this->frr_anexo =  $val;
}

public function setFrr_data($val)
{
$this->frr_data =  $val;
}


} 

?>

