
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ForumTopico
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  forum_topico
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class ForumTopico
{ 
private $frt_id;

private $frt_topico;



public function ForumTopico()
{

}




public function getFrt_id()
{
return $this->frt_id;
}

public function getFrt_topico()
{
return $this->frt_topico;
}



public function setFrt_id($val)
{
$this->frt_id =  $val;
}

public function setFrt_topico($val)
{
$this->frt_topico =  $val;
}


} 

?>

