
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Gabarito
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  gabarito
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Gabarito
{ 
private $gbt_id;

private $gbt_exercicio;
private $gbt_questao;
private $gbt_resposta;



public function Gabarito()
{

}




public function getGbt_id()
{
return $this->gbt_id;
}

public function getGbt_exercicio()
{
return $this->gbt_exercicio;
}

public function getGbt_questao()
{
return $this->gbt_questao;
}

public function getGbt_resposta()
{
return $this->gbt_resposta;
}



public function setGbt_id($val)
{
$this->gbt_id =  $val;
}

public function setGbt_exercicio($val)
{
$this->gbt_exercicio =  $val;
}

public function setGbt_questao($val)
{
$this->gbt_questao =  $val;
}

public function setGbt_resposta($val)
{
$this->gbt_resposta =  $val;
}


} 

?>

