
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Galeria
* GENERATION DATE:  02.03.2016
* FOR MYSQL TABLE:  galeria
* FOR MYSQL DB:     casar
* -------------------------------------------------------
* CODE GENERATED BY:
* @Lombardi
* -------------------------------------------------------
*
*/



class Galeria
{ 
	private $glr_idgaleria;

	private $glr_nome;
	private $glr_arquivo;
	private $glr_descricao;
	private $glr_data;
	private $glr_categoria;
	private $glr_visualizacoes;



	public function Galeria()
	{

	}




	public function getGlr_idgaleria()
	{
		return $this->glr_idgaleria;
	}

	public function getGlr_nome()
	{
		return $this->glr_nome;
	}

	public function getGlr_arquivo()
	{
		return $this->glr_arquivo;
	}

	public function getGlr_descricao()
	{
		return $this->glr_descricao;
	}

	public function getGlr_data()
	{
		return $this->glr_data;
	}

	public function getGlr_categoria()
	{
		return $this->glr_categoria;
	}

	public function getGlr_visualizacoes()
	{
		return $this->glr_visualizacoes;
	}



	public function setGlr_idgaleria($val)
	{
		$this->glr_idgaleria =  $val;
	}

	public function setGlr_nome($val)
	{
		$this->glr_nome =  $val;
	}

	public function setGlr_arquivo($val)
	{
		$this->glr_arquivo =  $val;
	}

	public function setGlr_descricao($val)
	{
		$this->glr_descricao =  $val;
	}

	public function setGlr_data($val)
	{
		$this->glr_data = $val;
	}

	public function setGlr_categoria($val)
	{
		$this->glr_categoria = $val;
	}

	public function setGlr_visualizacoes($val)
	{
		$this->glr_visualizacoes =  $val;
	}

	
} 

?>

