
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        GrauInstrucao
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  grau_instrucao
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class GrauInstrucao
{ 
private $grt_id;

private $grt_instrucao;



public function GrauInstrucao()
{

}




public function getGrt_id()
{
return $this->grt_id;
}

public function getGrt_instrucao()
{
return $this->grt_instrucao;
}



public function setGrt_id($val)
{
$this->grt_id =  $val;
}

public function setGrt_instrucao($val)
{
$this->grt_instrucao =  $val;
}


} 

?>

