
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        GrupoMensagem
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  gupo_mensagem
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class GrupoMensagem
{ 
private $gms_id;

private $gms_grupo;
private $gms_usuario;



public function GrupoMensagem()
{

}




public function getGms_id()
{
return $this->gms_id;
}

public function getGms_grupo()
{
return $this->gms_grupo;
}

public function getGms_usuario()
{
return $this->gms_usuario;
}



public function setGms_id($val)
{
$this->gms_id =  $val;
}

public function setGms_grupo($val)
{
$this->gms_grupo =  $val;
}

public function setGms_usuario($val)
{
$this->gms_usuario =  $val;
}


} 

?>

