
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        IdentificacaoEmail
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  identificacao_email
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class IdentificacaoEmail
{ 
private $dml_id;

private $dml_identificacao;



public function IdentificacaoEmail()
{

}




public function getDml_id()
{
return $this->dml_id;
}

public function getDml_identificacao()
{
return $this->dml_identificacao;
}



public function setDml_id($val)
{
$this->dml_id =  $val;
}

public function setDml_identificacao($val)
{
$this->dml_identificacao =  $val;
}


} 

?>

