
	<?php
			/*
			*
			* -------------------------------------------------------
			* CLASSNAME:        IdentificacaoEmail
			* GENERATION DATE:  11.06.2015
			* FOR MYSQL TABLE:  identificacao_email
			* FOR MYSQL DB:     hcb_criancas
			* -------------------------------------------------------
			* CODE GENERATED BY:
			* @MURANO DESIGN
			* -------------------------------------------------------
			*
			*/



			class IdentificacaoEmail
			{ 
			private $idn_id;

			private $idn_identificacao;



			public function IdentificacaoEmail()
			{

			}




			public function getidn_id()
			{
			return $this->idn_id;
			}

			public function getidn_identificacao()
			{
			return $this->idn_identificacao;
			}



			public function setidn_id($val)
			{
			$this->idn_id =  $val;
			}

			public function setidn_identificacao($val)
			{
			$this->idn_identificacao =  $val;
			}


			} 

			?>

