
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        LiberarCapitulo
* GENERATION DATE:  07.03.2016
* FOR MYSQL TABLE:  liberar_capitulo
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/

class LiberarCapitulo
{
    private $lbr_id;

    private $lbr_escola;
    private $lbr_capitulo;
    private $lbr_livro;
    private $lbr_status;


public function LiberarCapitulo()
{

}



public function getLbr_id()
{
    return $this->lbr_id;
}

public function getLbr_escola()
{
    return $this->lbr_escola;
}

public function getLbr_capitulo()
{
    return $this->lbr_capitulo;
}

public function getLbr_livro()
{
    return $this->lbr_livro;
}
public function getLbr_status()
{
    return $this->lbr_status;
}



public function setLbr_id($val)
{
    $this->lbr_id =  $val;
}

public function setLbr_escola($val)
{
    $this->lbr_escola =  $val;
}

public function setLbr_capitulo($val)
{
    $this->lbr_capitulo =  $val;
}

public function setLbr_livro($val)
{
    $this->lbr_livro =  $val;
}
public function setLbr_status($val)
{
    $this->lbr_status =  $val;
}

}

?>

    