
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Perfil
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  perfil
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Perfil
{ 
private $prf_id;

private $prf_perfil;

private $prf_url;

private $prf_pagina;



public function Perfil()
{

}




public function getPrf_id()
{
return $this->prf_id;
}

public function getPrf_perfil()
{
return $this->prf_perfil;
}

public function getPrf_url(){
    return $this->prf_url;
}

public function getPrf_pagina(){
    return $this->prf_pagina;
}


public function setPrf_id($val)
{
$this->prf_id =  $val;
}

public function setPrf_perfil($val)
{
$this->prf_perfil =  $val;
}

public function setPrf_url($val){
$this->prf_url = $val;
}

public function setPrf_pagina($val){
$this->prf_pagina = $val;
}


} 

?>

