
        <?php
        /*
        *
        * -------------------------------------------------------
        * CLASSNAME:        Periodo
        * GENERATION DATE:  14.04.2016
        * FOR MYSQL TABLE:  periodo
        * FOR MYSQL DB:     hcb_criancas_teste
        * -------------------------------------------------------
        * CODE GENERATED BY:
        * @MURANO DESIGN
        * -------------------------------------------------------
        *
        */

        class Periodo
        {
        private $prd_id;
    
            private $prd_periodo;
        

    public function Periodo()
    {

    }
    

    
        public function getPrd_id()
        {
        return $this->prd_id;
        }
        
        public function getPrd_periodo()
        {
        return $this->prd_periodo;
        }
        

    
        public function setPrd_id($val)
        {
            $this->prd_id =  $val;
        }
    
        public function setPrd_periodo($val)
        {
            $this->prd_periodo =  $val;
        }
    
    }

    ?>

    