
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Questao
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  questao
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Questao
{ 
private $qst_id;

private $qst_numero;
private $qst_questao;
private $qst_exercicio;



public function Questao()
{

}




public function getQst_id()
{
return $this->qst_id;
}

public function getQst_numero()
{
return $this->qst_numero;
}

public function getQst_questao()
{
return $this->qst_questao;
}

public function getQst_exercicio()
{
return $this->qst_exercicio;
}



public function setQst_id($val)
{
$this->qst_id =  $val;
}

public function setQst_numero($val)
{
$this->qst_numero =  $val;
}

public function setQst_questao($val)
{
$this->qst_questao =  $val;
}

public function setQst_exercicio($val)
{
$this->qst_exercicio =  $val;
}


} 

?>

