
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        RegistroGaleria
* GENERATION DATE:  21.03.2016
* FOR MYSQL TABLE:  registro_galeria
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/

class RegistroGaleria
{
private $rgg_id;

    private $rgg_escola;
    private $rgg_usuario;
    private $rgg_menu_galeria;
    private $rgg_download_galeria;
    private $rgg_data;
        

    public function RegistroGaleria()
    {

    }
    

    
    public function getRgg_id()
    {
    return $this->rgg_id;
    }
    
    public function getRgg_escola()
    {
    return $this->rgg_escola;
    }
    
    public function getRgg_usuario()
    {
    return $this->rgg_usuario;
    }
    
    public function getRgg_menu_galeria()
    {
    return $this->rgg_menu_galeria;
    }
    
    public function getRgg_download_galeria()
    {
    return $this->rgg_download_galeria;
    }
    
    public function getRgg_data()
    {
    return $this->rgg_data;
    }
        

    
    public function setRgg_id($val)
    {
        $this->rgg_id =  $val;
    }

    public function setRgg_escola($val)
    {
        $this->rgg_escola =  $val;
    }

    public function setRgg_usuario($val)
    {
        $this->rgg_usuario =  $val;
    }

    public function setRgg_menu_galeria($val)
    {
        $this->rgg_menu_galeria =  $val;
    }

    public function setRgg_download_galeria($val)
    {
        $this->rgg_download_galeria =  $val;
    }

    public function setRgg_data($val)
    {
        $this->rgg_data =  $val;
    }

}

?>

    