
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        ResgistroAcesso
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  registro_acesso
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class ResgistroAcesso
{ 
private $rgc_id;

private $rgc_usuario;
private $rgc_exercicio;
private $rgc_inicio;
private $rgc_fim;



public function ResgistroAcesso()
{

}


public function getRgc_id()
{
return $this->rgc_id;
}

public function getRgc_usuario()
{
return $this->rgc_usuario;
}

public function getRgc_exercicio()
{
return $this->rgc_exercicio;
}

public function getRgc_inicio()
{
return $this->rgc_inicio;
}

public function getRgc_fim()
{
return $this->rgc_fim;
}



public function setRgc_id($val)
{
$this->rgc_id =  $val;
}

public function setRgc_usuario($val)
{
$this->rgc_usuario =  $val;
}

public function setRgc_exercicio($val)
{
$this->rgc_exercicio =  $val;
}

public function setRgc_inicio($val)
{
$this->rgc_inicio =  $val;
}

public function setRgc_fim($val)
{
$this->rgc_fim =  $val;
}


} 

?>

