
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        RespostaTxt
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  resposta_txt
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class RespostaTxt
{ 
private $rspt_id;

private $rspt_usuario;
private $rspt_exercicio;
private $rspt_questao;
private $rspt_resposta;



public function RespostaTxt()
{

}




public function getRspt_id()
{
return $this->rspt_id;
}

public function getRspt_usuario()
{
return $this->rspt_usuario;
}

public function getRspt_exercicio()
{
return $this->rspt_exercicio;
}

public function getRspt_questao()
{
return $this->rspt_questao;
}

public function getRspt_resposta()
{
return $this->rspt_resposta;
}



public function setRspt_id($val)
{
$this->rspt_id =  $val;
}

public function setRspt_usuario($val)
{
$this->rspt_usuario =  $val;
}

public function setRspt_exercicio($val)
{
$this->rspt_exercicio =  $val;
}

public function setRspt_questao($val)
{
$this->rspt_questao =  $val;
}

public function setRspt_resposta($val)
{
$this->rspt_resposta =  $val;
}


} 

?>

