
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        RespostaMultipla
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  resposta_multipla
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class RespostaMultipla
{ 
private $rspm_id;

private $rspm_aluno;
private $rspm_questao;
private $rspm_resposta;



public function RespostaMultipla()
{

}




public function getRspm_id()
{
return $this->rspm_id;
}

public function getRspm_aluno()
{
return $this->rspm_aluno;
}

public function getRspm_questao()
{
return $this->rspm_questao;
}

public function getRspm_resposta()
{
return $this->rspm_resposta;
}



public function setRspm_id($val)
{
$this->rspm_id =  $val;
}

public function setRspm_aluno($val)
{
$this->rspm_aluno =  $val;
}

public function setRspm_questao($val)
{
$this->rspm_questao =  $val;
}

public function setRspm_resposta($val)
{
$this->rspm_resposta =  $val;
}


} 

?>

