
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        RespostaMultipla
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  resposta_multipla
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class RespostaMultipla
{ 
private $rspm_id;

private $rspm_usuario;
private $rspm_exercicio;
private $rspm_questao;
private $rspm_resposta;



public function RespostaMultipla()
{

}




public function getRspm_id()
{
return $this->rspm_id;
}

public function getRspm_usuario()
{
return $this->rspm_usuario;
}

public function getRspm_exercicio()
{
return $this->rspm_exercicio;
}

public function getRspm_questao()
{
return $this->rspm_questao;
}

public function getRspm_resposta()
{
return $this->rspm_resposta;
}



public function setRspm_id($val)
{
$this->rspm_id =  $val;
}

public function setRspm_usuario($val)
{
$this->rspm_usuario =  $val;
}
public function setRspm_exercicio($val)
{
$this->rspm_exercicio =  $val;
}

public function setRspm_questao($val)
{
$this->rspm_questao =  $val;
}

public function setRspm_resposta($val)
{
$this->rspm_resposta =  $val;
}


} 

?>

