
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Serie
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  serie
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Serie
{ 
private $sri_id;

private $sri_serie;



public function Serie()
{

}




public function getSri_id()
{
return $this->sri_id;
}

public function getSri_serie()
{
return $this->sri_serie;
}



public function setSri_id($val)
{
$this->sri_id =  $val;
}

public function setSri_serie($val)
{
$this->sri_serie =  $val;
}


} 

?>

