
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Tema
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  tema
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Tema
{ 
private $tm_id;

private $tm_tema;
private $tm_capitulo;



public function Tema()
{

}




public function getTm_id()
{
return $this->tm_id;
}

public function getTm_tema()
{
return $this->tm_tema;
}

public function getTm_capitulo()
{
return $this->tm_capitulo;
}



public function setTm_id($val)
{
$this->tm_id =  $val;
}

public function setTm_tema($val)
{
$this->tm_tema =  $val;
}

public function setTm_capitulo($val)
{
$this->tm_capitulo =  $val;
}


} 

?>

