
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        TipoEvento
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  tipo_evento
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class TipoEvento
{ 
private $tpv_id;

private $tpv_evento;



public function TipoEvento()
{

}




public function getTpv_id()
{
return $this->tpv_id;
}

public function getTpv_evento()
{
return $this->tpv_evento;
}



public function setTpv_id($val)
{
$this->tpv_id =  $val;
}

public function setTpv_evento($val)
{
$this->tpv_evento =  $val;
}


} 

?>

