
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        TipoEmail
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  tipo_email
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class TipoEmail
{ 
private $tml_id;

private $tml_tipo;



public function TipoEmail()
{

}




public function getTml_id()
{
return $this->tml_id;
}

public function getTml_tipo()
{
return $this->tml_tipo;
}



public function setTml_id($val)
{
$this->tml_id =  $val;
}

public function setTml_tipo($val)
{
$this->tml_tipo =  $val;
}


} 

?>

