
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        TipoExercicio
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  tipo_exercicio
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class TipoExercicio
{ 
private $txr_id;

private $txr_tipo;



public function TipoExercicio()
{

}




public function getTxr_id()
{
return $this->txr_id;
}

public function getTxr_tipo()
{
return $this->txr_tipo;
}



public function setTxr_id($val)
{
$this->txr_id =  $val;
}

public function setTxr_tipo($val)
{
$this->txr_tipo =  $val;
}


} 

?>

