
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        TipoEscola
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  tipo_escola
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class TipoEscola
{ 
private $tps_id;

private $tps_tipo_escola;



public function TipoEscola()
{

}




public function getTps_id()
{
return $this->tps_id;
}

public function getTps_tipo_escola()
{
return $this->tps_tipo_escola;
}



public function setTps_id($val)
{
$this->tps_id =  $val;
}

public function setTps_tipo_escola($val)
{
$this->tps_tipo_escola =  $val;
}


} 

?>

