
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        Usuario
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  usuario
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class Usuario
{ 
private $usr_id;

private $usr_nome;
private $usr_data_nascimento;
private $usr_endereco;
private $usr_escola;
private $usr_data_entrada_escola;
private $usr_nse;
private $usr_perfil;
private $usr_login;
private $usr_senha;
private $usr_cpf;
private $usr_rg;
private $usr_imagem;


public function Usuario()
{

}




public function getUsr_id()
{
return $this->usr_id;
}

public function getUsr_nome()
{
return $this->usr_nome;
}

public function getUsr_data_nascimento()
{
return $this->usr_data_nascimento;
}

public function getUsr_endereco()
{
return $this->usr_endereco;
}

public function getUsr_escola()
{
return $this->usr_escola;
}

public function getUsr_data_entrada_escola()
{
return $this->usr_data_entrada_escola;
}

public function getUsr_nse()
{
return $this->usr_nse;
}

public function getUsr_perfil()
{
return $this->usr_perfil;
}

public function getUsr_login()
{
return $this->usr_login;
}

public function getUsr_senha()
{
return $this->usr_senha;
}

public function getUsr_rg()
{
return $this->usr_rg;
}
public function getUsr_cpf()
{
return $this->usr_cpf;
}
public function getUsr_imagem()
{
return $this->usr_imagem;
}


public function setUsr_id($val)
{
$this->usr_id =  $val;
}

public function setUsr_nome($val)
{
$this->usr_nome =  $val;
}

public function setUsr_data_nascimento($val)
{
$this->usr_data_nascimento =  $val;
}

public function setUsr_endereco($val)
{
$this->usr_endereco =  $val;
}

public function setUsr_escola($val)
{
$this->usr_escola =  $val;
}

public function setUsr_data_entrada_escola($val)
{
$this->usr_data_entrada_escola =  $val;
}

public function setUsr_nse($val)
{
$this->usr_nse =  $val;
}

public function setUsr_perfil($val)
{
$this->usr_perfil =  $val;
}
public function setUsr_login($val)
{
$this->usr_login =  $val;
}
public function setUsr_senha($val)
{
$this->usr_senha =  $val;
}
public function setUsr_rg($val)
{
$this->usr_rg =  $val;
}
public function setUsr_cpf($val)
{
$this->usr_cpf =  $val;
}
public function setUsr_imagem($val)
{
$this->usr_imagem =  $val;
}
} 

?>

