
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        UsuarioGrupoMensagem
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  usuario_grupo_mensagem
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class UsuarioGrupoMensagem
{ 
private $sgm_id;

private $sgm_grupo;
private $sgm_usuario;



public function UsuarioGrupoMensagem()
{

}




public function getSgm_id()
{
return $this->sgm_id;
}

public function getSgm_grupo()
{
return $this->sgm_grupo;
}

public function getSgm_usuario()
{
return $this->sgm_usuario;
}



public function setSgm_id($val)
{
$this->sgm_id =  $val;
}

public function setSgm_grupo($val)
{
$this->sgm_grupo =  $val;
}

public function setSgm_usuario($val)
{
$this->sgm_usuario =  $val;
}


} 

?>

