
<?php
			/*
			*
			* -------------------------------------------------------
			* CLASSNAME:        UsuarioGrupoMensagem
			* GENERATION DATE:  11.06.2015
			* FOR MYSQL TABLE:  usuario_grupo_mensagem
			* FOR MYSQL DB:     hcb_criancas
			* -------------------------------------------------------
			* CODE GENERATED BY:
			* @MURANO DESIGN
			* -------------------------------------------------------
			*
			*/



			class UsuarioGrupoMensagem
			{ 
			private $ugm_id;

			private $ugm_grupo;
			private $ugm_usuario;



			public function UsuarioGrupoMensagem()
			{

			}




			public function getugm_id()
			{
			return $this->ugm_id;
			}

			public function getugm_grupo()
			{
			return $this->ugm_grupo;
			}

			public function getugm_usuario()
			{
			return $this->ugm_usuario;
			}



			public function setugm_id($val)
			{
			$this->ugm_id =  $val;
			}

			public function setugm_grupo($val)
			{
			$this->ugm_grupo =  $val;
			}

			public function setugm_usuario($val)
			{
			$this->ugm_usuario =  $val;
			}


			} 

			?>

