
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        UsuarioVariavel
* GENERATION DATE:  11.06.2015
* FOR MYSQL TABLE:  usuario_variavel
* FOR MYSQL DB:     hcb_criancas
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/



class UsuarioVariavel
{ 
private $usv_id;

private $usv_usuario;
private $usv_ano_letivo;
private $usv_serie;
private $usv_grau_instrucao;
private $usv_categoria_funcional;
private $usv_grupo;



public function UsuarioVariavel()
{

}




public function getUsv_id()
{
return $this->usv_id;
}

public function getUsv_usuario()
{
return $this->usv_usuario;
}

public function getUsv_ano_letivo()
{
return $this->usv_ano_letivo;
}

public function getUsv_serie()
{
return $this->usv_serie;
}

public function getUsv_grau_instrucao()
{
return $this->usv_grau_instrucao;
}

public function getUsv_categoria_funcional()
{
return $this->usv_categoria_funcional;
}

public function getUsv_grupo()
{
return $this->usv_grupo;
}



public function setUsv_id($val)
{
$this->usv_id =  $val;
}

public function setUsv_usuario($val)
{
$this->usv_usuario =  $val;
}

public function setUsv_ano_letivo($val)
{
$this->usv_ano_letivo =  $val;
}

public function setUsv_serie($val)
{
$this->usv_serie =  $val;
}

public function setUsv_grau_instrucao($val)
{
$this->usv_grau_instrucao =  $val;
}

public function setUsv_categoria_funcional($val)
{
$this->usv_categoria_funcional =  $val;
}

public function setUsv_grupo($val)
{
$this->usv_grupo =  $val;
}


} 

?>

