
<?php
/*
*
* -------------------------------------------------------
* CLASSNAME:        DocumentoRetorno
* GENERATION DATE:  05.09.2016
* FOR MYSQL TABLE:  documento_retorno
* FOR MYSQL DB:     hcb
* -------------------------------------------------------
* CODE GENERATED BY:
* @MURANO DESIGN
* -------------------------------------------------------
*
*/

$path = $_SESSION['PATH_SYS'];

include_once($path['dao'].'DocumentoRetornoDAO.php');


/**
 * Description of DocumentoRetornoController
 *
 * @author MURANO DESIGN
 */

class DocumentoRetornoController {

    private $documentoretornoDAO;

    public function  __construct() {
        $this->documentoretornoDAO = new DocumentoRetornoDAO(new DataAccess());
    }

    public function insertDocumentoRetorno($documentoretorno) {
        return $this->documentoretornoDAO->insertDocumentoRetorno($documentoretorno);
    }

    public function updateDocumentoRetorno($documentoretorno) {
        return $this->documentoretornoDAO->updateDocumentoRetorno($documentoretorno);
    }

    public function deleteDocumentoRetorno($documentoretorno) {
        return $this->documentoretornoDAO->deleteDocumentoRetorno($documentoretorno);
    }

    public function selectByIdDocumentoRetorno($idDocumentoRetorno){
        $documentoretorno = $this->documentoretornoDAO->selectByIdDocumentoRetorno($idDocumentoRetorno);
        return  $documentoretorno;
    }

    public function selectAllDocumentoRetorno(){
        $documentoretorno = $this->documentoretornoDAO->selectAllDocumentoRetorno();
        return  $documentoretorno;
    }

    public function insertParcial($documentoRetorno)
    {
        return $this->documentoretornoDAO->insertParcial($documentoRetorno);
    }

    public function listarEscola($idEscola)
    {
        return $this->documentoretornoDAO->listarEscola($idEscola);
    }

    public function visualizar($idRetorno)
    {
        return $this->documentoretornoDAO->visualizar($idRetorno);
    }

    public function listarDocumento($idDocumento)
    {
        return $this->documentoretornoDAO->listarDocumento($idDocumento);
    }
    
    public function getRetornosByEscolaAndEnvio($idesc, $iddoe) {
        return $this->documentoretornoDAO->getRetornosByEscolaAndEnvio($idesc, $iddoe);
    }
    public function isPendenciasRetornoHospital()
    {
        return $this->documentoretornoDAO->isPendenciasRetornoHospital();
    }
}
?>